/* tslint:disable */
/* eslint-disable */
/**
 * Blog Core API
 * Blog Core API description
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthUserCreateDto
 */
export interface AuthUserCreateDto {
    /**
     * 
     * @type {string}
     * @memberof AuthUserCreateDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserCreateDto
     */
    nickName: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserCreateDto
     */
    password: string;
}

/**
 * Check if a given object implements the AuthUserCreateDto interface.
 */
export function instanceOfAuthUserCreateDto(value: object): value is AuthUserCreateDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('nickName' in value) || value['nickName'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AuthUserCreateDtoFromJSON(json: any): AuthUserCreateDto {
    return AuthUserCreateDtoFromJSONTyped(json, false);
}

export function AuthUserCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthUserCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'nickName': json['nickName'],
        'password': json['password'],
    };
}

export function AuthUserCreateDtoToJSON(json: any): AuthUserCreateDto {
    return AuthUserCreateDtoToJSONTyped(json, false);
}

export function AuthUserCreateDtoToJSONTyped(value?: AuthUserCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'nickName': value['nickName'],
        'password': value['password'],
    };
}

