/* tslint:disable */
/* eslint-disable */
/**
 * Blog Core API
 * Blog Core API description
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthUserChangePasswordDto
 */
export interface AuthUserChangePasswordDto {
    /**
     * 
     * @type {string}
     * @memberof AuthUserChangePasswordDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserChangePasswordDto
     */
    newPassword: string;
}

/**
 * Check if a given object implements the AuthUserChangePasswordDto interface.
 */
export function instanceOfAuthUserChangePasswordDto(value: object): value is AuthUserChangePasswordDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function AuthUserChangePasswordDtoFromJSON(json: any): AuthUserChangePasswordDto {
    return AuthUserChangePasswordDtoFromJSONTyped(json, false);
}

export function AuthUserChangePasswordDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthUserChangePasswordDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'newPassword': json['newPassword'],
    };
}

export function AuthUserChangePasswordDtoToJSON(json: any): AuthUserChangePasswordDto {
    return AuthUserChangePasswordDtoToJSONTyped(json, false);
}

export function AuthUserChangePasswordDtoToJSONTyped(value?: AuthUserChangePasswordDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'newPassword': value['newPassword'],
    };
}

