/* tslint:disable */
/* eslint-disable */
/**
 * Blog Core API
 * Blog Core API description
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthUserSignInDto
 */
export interface AuthUserSignInDto {
    /**
     * 
     * @type {string}
     * @memberof AuthUserSignInDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserSignInDto
     */
    password: string;
}

/**
 * Check if a given object implements the AuthUserSignInDto interface.
 */
export function instanceOfAuthUserSignInDto(value: object): value is AuthUserSignInDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AuthUserSignInDtoFromJSON(json: any): AuthUserSignInDto {
    return AuthUserSignInDtoFromJSONTyped(json, false);
}

export function AuthUserSignInDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthUserSignInDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function AuthUserSignInDtoToJSON(json: any): AuthUserSignInDto {
    return AuthUserSignInDtoToJSONTyped(json, false);
}

export function AuthUserSignInDtoToJSONTyped(value?: AuthUserSignInDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

