/* tslint:disable */
/* eslint-disable */
/**
 * Blog Core API
 * Blog Core API description
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CognitoSignInTokenResponseDto
 */
export interface CognitoSignInTokenResponseDto {
    /**
     * Access token for authenticated requests
     * @type {string}
     * @memberof CognitoSignInTokenResponseDto
     */
    AccessToken: string;
    /**
     * Refresh token for renewing the session
     * @type {string}
     * @memberof CognitoSignInTokenResponseDto
     */
    RefreshToken: string;
    /**
     * Expiration time of the access token in seconds
     * @type {number}
     * @memberof CognitoSignInTokenResponseDto
     */
    ExpiresIn: number;
}

/**
 * Check if a given object implements the CognitoSignInTokenResponseDto interface.
 */
export function instanceOfCognitoSignInTokenResponseDto(value: object): value is CognitoSignInTokenResponseDto {
    if (!('AccessToken' in value) || value['AccessToken'] === undefined) return false;
    if (!('RefreshToken' in value) || value['RefreshToken'] === undefined) return false;
    if (!('ExpiresIn' in value) || value['ExpiresIn'] === undefined) return false;
    return true;
}

export function CognitoSignInTokenResponseDtoFromJSON(json: any): CognitoSignInTokenResponseDto {
    return CognitoSignInTokenResponseDtoFromJSONTyped(json, false);
}

export function CognitoSignInTokenResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CognitoSignInTokenResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'AccessToken': json['AccessToken'],
        'RefreshToken': json['RefreshToken'],
        'ExpiresIn': json['ExpiresIn'],
    };
}

export function CognitoSignInTokenResponseDtoToJSON(json: any): CognitoSignInTokenResponseDto {
    return CognitoSignInTokenResponseDtoToJSONTyped(json, false);
}

export function CognitoSignInTokenResponseDtoToJSONTyped(value?: CognitoSignInTokenResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'AccessToken': value['AccessToken'],
        'RefreshToken': value['RefreshToken'],
        'ExpiresIn': value['ExpiresIn'],
    };
}

