/* tslint:disable */
/* eslint-disable */
/**
 * Blog Core API
 * Blog Core API description
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CognitoSignInResponseDto
 */
export interface CognitoSignInResponseDto {
    /**
     * The challenge required for further actions (e.g., NEW_PASSWORD_REQUIRED)
     * @type {string}
     * @memberof CognitoSignInResponseDto
     */
    ChallengeName: string;
}

/**
 * Check if a given object implements the CognitoSignInResponseDto interface.
 */
export function instanceOfCognitoSignInResponseDto(value: object): value is CognitoSignInResponseDto {
    if (!('ChallengeName' in value) || value['ChallengeName'] === undefined) return false;
    return true;
}

export function CognitoSignInResponseDtoFromJSON(json: any): CognitoSignInResponseDto {
    return CognitoSignInResponseDtoFromJSONTyped(json, false);
}

export function CognitoSignInResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CognitoSignInResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'ChallengeName': json['ChallengeName'],
    };
}

export function CognitoSignInResponseDtoToJSON(json: any): CognitoSignInResponseDto {
    return CognitoSignInResponseDtoToJSONTyped(json, false);
}

export function CognitoSignInResponseDtoToJSONTyped(value?: CognitoSignInResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ChallengeName': value['ChallengeName'],
    };
}

