/* tslint:disable */
/* eslint-disable */
/**
 * Blog Core API
 * Blog Core API description
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageableParams
 */
export interface PageableParams {
    /**
     * Page number
     * @type {number}
     * @memberof PageableParams
     */
    page?: number;
    /**
     * Page size
     * @type {number}
     * @memberof PageableParams
     */
    size?: number;
}

/**
 * Check if a given object implements the PageableParams interface.
 */
export function instanceOfPageableParams(value: object): value is PageableParams {
    return true;
}

export function PageableParamsFromJSON(json: any): PageableParams {
    return PageableParamsFromJSONTyped(json, false);
}

export function PageableParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableParams {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function PageableParamsToJSON(json: any): PageableParams {
    return PageableParamsToJSONTyped(json, false);
}

export function PageableParamsToJSONTyped(value?: PageableParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'size': value['size'],
    };
}

