/* tslint:disable */
/* eslint-disable */
/**
 * Blog Core API
 * Blog Core API description
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pageable } from './Pageable';
import {
    PageableFromJSON,
    PageableFromJSONTyped,
    PageableToJSON,
    PageableToJSONTyped,
} from './Pageable';
import type { PostDto } from './PostDto';
import {
    PostDtoFromJSON,
    PostDtoFromJSONTyped,
    PostDtoToJSON,
    PostDtoToJSONTyped,
} from './PostDto';

/**
 * 
 * @export
 * @interface PostControllerGetPosts200Response
 */
export interface PostControllerGetPosts200Response {
    /**
     * Pageable params
     * @type {Pageable}
     * @memberof PostControllerGetPosts200Response
     */
    pageable: Pageable;
    /**
     * Total pages
     * @type {number}
     * @memberof PostControllerGetPosts200Response
     */
    totalPages: number;
    /**
     * Total elements
     * @type {number}
     * @memberof PostControllerGetPosts200Response
     */
    totalElements: number;
    /**
     * 
     * @type {Array<PostDto>}
     * @memberof PostControllerGetPosts200Response
     */
    content?: Array<PostDto>;
}

/**
 * Check if a given object implements the PostControllerGetPosts200Response interface.
 */
export function instanceOfPostControllerGetPosts200Response(value: object): value is PostControllerGetPosts200Response {
    if (!('pageable' in value) || value['pageable'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('totalElements' in value) || value['totalElements'] === undefined) return false;
    return true;
}

export function PostControllerGetPosts200ResponseFromJSON(json: any): PostControllerGetPosts200Response {
    return PostControllerGetPosts200ResponseFromJSONTyped(json, false);
}

export function PostControllerGetPosts200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostControllerGetPosts200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'pageable': PageableFromJSON(json['pageable']),
        'totalPages': json['totalPages'],
        'totalElements': json['totalElements'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(PostDtoFromJSON)),
    };
}

export function PostControllerGetPosts200ResponseToJSON(json: any): PostControllerGetPosts200Response {
    return PostControllerGetPosts200ResponseToJSONTyped(json, false);
}

export function PostControllerGetPosts200ResponseToJSONTyped(value?: PostControllerGetPosts200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pageable': PageableToJSON(value['pageable']),
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(PostDtoToJSON)),
    };
}

