/* tslint:disable */
/* eslint-disable */
/**
 * Blog Core API
 * Blog Core API description
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostUpdateDto
 */
export interface PostUpdateDto {
    /**
     * The updated title of the post
     * @type {string}
     * @memberof PostUpdateDto
     */
    title?: string;
    /**
     * The updated slug for the post
     * @type {string}
     * @memberof PostUpdateDto
     */
    slug?: string;
    /**
     * The updated main content of the post
     * @type {string}
     * @memberof PostUpdateDto
     */
    content?: string;
    /**
     * Updated array of tag names (strings)
     * @type {Array<string>}
     * @memberof PostUpdateDto
     */
    tags?: Array<string>;
    /**
     * Updated time to read the post, in minutes
     * @type {number}
     * @memberof PostUpdateDto
     */
    timeToRead?: number;
}

/**
 * Check if a given object implements the PostUpdateDto interface.
 */
export function instanceOfPostUpdateDto(value: object): value is PostUpdateDto {
    return true;
}

export function PostUpdateDtoFromJSON(json: any): PostUpdateDto {
    return PostUpdateDtoFromJSONTyped(json, false);
}

export function PostUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostUpdateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'content': json['content'] == null ? undefined : json['content'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'timeToRead': json['timeToRead'] == null ? undefined : json['timeToRead'],
    };
}

export function PostUpdateDtoToJSON(json: any): PostUpdateDto {
    return PostUpdateDtoToJSONTyped(json, false);
}

export function PostUpdateDtoToJSONTyped(value?: PostUpdateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'slug': value['slug'],
        'content': value['content'],
        'tags': value['tags'],
        'timeToRead': value['timeToRead'],
    };
}

