/* tslint:disable */
/* eslint-disable */
/**
 * Blog Core API
 * Blog Core API description
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostCreateDto
 */
export interface PostCreateDto {
    /**
     * The title of the post
     * @type {string}
     * @memberof PostCreateDto
     */
    title: string;
    /**
     * The slug for the post
     * @type {string}
     * @memberof PostCreateDto
     */
    slug: string;
    /**
     * The main content of the post
     * @type {string}
     * @memberof PostCreateDto
     */
    content: string;
    /**
     * Array of tag names (strings)
     * @type {Array<string>}
     * @memberof PostCreateDto
     */
    tags: Array<string>;
    /**
     * Time to read the post, in minutes
     * @type {number}
     * @memberof PostCreateDto
     */
    timeToRead: number;
}

/**
 * Check if a given object implements the PostCreateDto interface.
 */
export function instanceOfPostCreateDto(value: object): value is PostCreateDto {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('timeToRead' in value) || value['timeToRead'] === undefined) return false;
    return true;
}

export function PostCreateDtoFromJSON(json: any): PostCreateDto {
    return PostCreateDtoFromJSONTyped(json, false);
}

export function PostCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'slug': json['slug'],
        'content': json['content'],
        'tags': json['tags'],
        'timeToRead': json['timeToRead'],
    };
}

export function PostCreateDtoToJSON(json: any): PostCreateDto {
    return PostCreateDtoToJSONTyped(json, false);
}

export function PostCreateDtoToJSONTyped(value?: PostCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'slug': value['slug'],
        'content': value['content'],
        'tags': value['tags'],
        'timeToRead': value['timeToRead'],
    };
}

