/* tslint:disable */
/* eslint-disable */
/**
 * Blog Core API
 * Blog Core API description
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pageable } from './Pageable';
import {
    PageableFromJSON,
    PageableFromJSONTyped,
    PageableToJSON,
    PageableToJSONTyped,
} from './Pageable';

/**
 * 
 * @export
 * @interface TagControllerGetTags200Response
 */
export interface TagControllerGetTags200Response {
    /**
     * Pageable params
     * @type {Pageable}
     * @memberof TagControllerGetTags200Response
     */
    pageable: Pageable;
    /**
     * Total pages
     * @type {number}
     * @memberof TagControllerGetTags200Response
     */
    totalPages: number;
    /**
     * Total elements
     * @type {number}
     * @memberof TagControllerGetTags200Response
     */
    totalElements: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof TagControllerGetTags200Response
     */
    content?: Array<object>;
}

/**
 * Check if a given object implements the TagControllerGetTags200Response interface.
 */
export function instanceOfTagControllerGetTags200Response(value: object): value is TagControllerGetTags200Response {
    if (!('pageable' in value) || value['pageable'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('totalElements' in value) || value['totalElements'] === undefined) return false;
    return true;
}

export function TagControllerGetTags200ResponseFromJSON(json: any): TagControllerGetTags200Response {
    return TagControllerGetTags200ResponseFromJSONTyped(json, false);
}

export function TagControllerGetTags200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagControllerGetTags200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'pageable': PageableFromJSON(json['pageable']),
        'totalPages': json['totalPages'],
        'totalElements': json['totalElements'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function TagControllerGetTags200ResponseToJSON(json: any): TagControllerGetTags200Response {
    return TagControllerGetTags200ResponseToJSONTyped(json, false);
}

export function TagControllerGetTags200ResponseToJSONTyped(value?: TagControllerGetTags200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pageable': PageableToJSON(value['pageable']),
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
        'content': value['content'],
    };
}

