/* tslint:disable */
/* eslint-disable */
/**
 * Blog Core API
 * Blog Core API description
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagCreateDto
 */
export interface TagCreateDto {
    /**
     * 
     * @type {string}
     * @memberof TagCreateDto
     */
    name: string;
}

/**
 * Check if a given object implements the TagCreateDto interface.
 */
export function instanceOfTagCreateDto(value: object): value is TagCreateDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function TagCreateDtoFromJSON(json: any): TagCreateDto {
    return TagCreateDtoFromJSONTyped(json, false);
}

export function TagCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function TagCreateDtoToJSON(json: any): TagCreateDto {
    return TagCreateDtoToJSONTyped(json, false);
}

export function TagCreateDtoToJSONTyped(value?: TagCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

