/* tslint:disable */
/* eslint-disable */
/**
 * Blog Core API
 * Blog Core API description
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagUpdateDto
 */
export interface TagUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof TagUpdateDto
     */
    name: string;
}

/**
 * Check if a given object implements the TagUpdateDto interface.
 */
export function instanceOfTagUpdateDto(value: object): value is TagUpdateDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function TagUpdateDtoFromJSON(json: any): TagUpdateDto {
    return TagUpdateDtoFromJSONTyped(json, false);
}

export function TagUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagUpdateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function TagUpdateDtoToJSON(json: any): TagUpdateDto {
    return TagUpdateDtoToJSONTyped(json, false);
}

export function TagUpdateDtoToJSONTyped(value?: TagUpdateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

